spring:
  application:
    name: zonas-espacios
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3307/zonas_espacios?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:zonas_app}
    password: ${SPRING_DATASOURCE_PASSWORD:zonas123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin123}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 300000

server:
  port: 8081
  address: 0.0.0.0

auth:
  jwt:
    secret: ${JWT_SECRET:parcial2-arqui-jwt-secret-key-2026-min-256-bits!!}
  internal-api-key: ${INTERNAL_API_KEY:internal-service-key-parcial2}
  usuarios-validate-url: ${MS_AUTH_VALIDATE:http://localhost:9090/api/auth/validate}
