

services:

  mysql-db:
    image: mysql:latest
    container_name: mysql-zonas
    restart: always
    environment:
      MYSQL_DATABASE: zonas_espacios
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: zonas_app
      MYSQL_PASSWORD: zonas123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: