apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-tickets
  namespace: parqueaderos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-tickets
  template:
    metadata:
      labels:
        app: postgres-tickets
    spec:
      containers:
      - name: postgres-tickets
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "tickets_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "123456"
        volumeMounts:
        - name: postgres-tickets-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-tickets-storage
        persistentVolumeClaim:
          claimName: postgres-tickets-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-tickets-pvc
  namespace: parqueaderos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-tickets
  namespace: parqueaderos
spec:
  selector:
    app: postgres-tickets
  ports:
  - port: 5432
    targetPort: 5432
